version: "3.7"
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "4801:80"
  web:
    build:
      context: ./phalcon
      dockerfile: Dockerfile
    ports:
      - "9001:80"
    volumes:
      - ./www:/var/www